# github管理配置
spring:
  application:
      name: CONFIG_SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.iam/xiasq/hyjf-rebuild.git
          searchPaths: config_files
          username: mx2012xshq@126.iam
          password: abcd1234

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:1111/eureka/
  instance:
    preferIpAddress: true