quartz:
  threadPool:
    threadCount: 10
  dataSource:
    quartzDataSource:
      URL: jdbc:mysql://106.14.154.224:3306/batch
      user: root
      password: Abcd1234
      maxConnections: 10

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
  resources:
    static-locations: classpath:/static/