spring:
  redis: 
    database: 0  
    # Redis服务器地址
    hostName: 123.57.155.17
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: RH06863b3e6
    # 连接池最大连接数（使用负值表示没有限制）
    pool: 
      max-active: 8  
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1  
      # 连接池中的最大空闲连接
      max-idle: 8  
      # 连接池中的最小空闲连接
      min-idle: 0  
    # 连接超时时间（毫秒）
    timeout: 0



rocketMQ:
  namesrvAddr: ${rocketMQ.namesrvAddr}
  #以业务名为consumerGroup名，事件为tag
  defaultProducerGroup : cs-iam
  defaultConsumerGroup : cs-iam
  group :
    couponGroup : CS_IAM_COUPON_GROUP
  topic :
    couponTopic : CS_IAM_COUPON_TOPIC
  tag :
    defaultTag : cs-iam

env.test: false
hyjf.activity.888.id: 37
hyjf.activity.regist.tzj.id: 39

